### ISSUE TITLE
make fix_ogvjs_dist more generic

### ISSUE THREAD

**Issue by rgaudin** [openzim/python_scraperlib#1]
the `fix_ogvjs_dist` script enables an installation of `videojs`, `ogvjs` and `videojs-ogvjs` to run from inside and outside a ZIM file.

the parameters of the script gives the impression that folder can be placed at any path of the output folder. It's not actually the case as a couple of hard-coded values lies in the script

``` JS
// assumes placed as ./xxx/
ZIM_IMG_NS = (IS_IN_ZIM) ? '../../../I/' : '';
...
target = ZIM_IMG_NS + "{vendors_path}/ogvjs/" + target;
```

Quick documentation on how to set this folder up and use it (`base` option) would be a good addition to the script as well.

**Comment by satyamtg** [comment]
Hi rgaudian, I want to get involved with the project and would like to take this forward.

**Comment by rgaudin** [comment]
Great, assign yourself and go ahead.

**Comment by satyamtg** [comment]
Hey @rgaudin , I have understood what the fix_ogvjs_dist.py does. However, I am having some difficulty in understanding this very issue. Could you please elaborate a little bit?

**Comment by rgaudin** [comment]
OK, so as you've guessed the script is mostly about rewriting paths inside ogvjs and all so that it can work on:

* a web server (the default case for the lib)
* a local file (we use that for testing)
* inside a ZIM file (with namespaces prefixes based on mime-type)

Current code only works if the final path is `<somefolder>/ogvjs/`. If one was to put that `ogvjs` folder inside `static/js/ogvjs` for instance, it wouldn't work as the rewriting of path assumes a single parent folder from that `ogvjs` one.

Is that clearer ?

**Comment by satyamtg** [comment]
Okay, so from what I can understand now, we assume that the path is somehow like <somefolder>/ogvjs. Now in the ZIM file, the javascript files would be in /-/<somefolder>/ogvjs and the .wasm ones would be in /I/<somefolder>/ogvjs. So, we need the namespace prefix as '../../../I/' and then we need to join <somefolder>/ogvjs to it. So, if <somefolder> is replaced with a folder tree, then the number of '../' would differ. We need to fix that such that a path such as <somefolder>/someotherfolder>/ogvjs would work. @rgaudin is my understanding right?

**Comment by rgaudin** [comment]
Yes, you got it right. We need to find out the depth of the destination folder and adjust the relative folder to rewind in the JS.

**Comment by satyamtg** [comment]
Hey @rgaudin , have a look at https://github.com/openzim/python_scraperlib/compare/master...satyamtg:more_generic_ogvjs
I have implemented some code to do the aforementioned. If you approve I can create a PR or else please suggest changes.
