### ISSUE TITLE
Extend zimscraperlib.zim to support more command arguments to zimwriterfs

### ISSUE THREAD

**Issue by satyamtg** [openzim/python_scraperlib#10]
Extend `ZimInfo` class to support more arguments as discussed here : https://github.com/openzim/sotoki/issues/107

**Comment by satyamtg** [comment]
@rgaudin @kelson42 , have most probably fixed this issue. However, youtube and nautilus would need to be updated to support the newer `to_zimwriterfs_args()`

**Comment by rgaudin** [comment]
Thanks 👍
