### ISSUE TITLE
Extend imaging module to handle optimization

### ISSUE THREAD

**Issue by satyamtg** [openzim/python_scraperlib#26]
Image optimization is something that's one of the most common tasks done by a scraper. We can extend the imaging module to have this incorporated in a well-tested manner in scraperlib and have support for various formats so that we do not face issues with this in individual scrapers. We can have something similar to the video module where we have presets and can even manage different optimizer versions. Maybe we can experiment  a bit here (since we plan to start having formats like WebP in scrapers. See https://github.com/openzim/sotoki/issues/151)

**Comment by rgaudin** [comment]
I'd like this to be an opportunity to:

* list available options per format
* compare (with data!) the quality/gain/speed of the various methods, including using in-python tools like Pillow.
* we should have sample data reflecting actual usage.

We should know what tool to use based on the kind of input we get. It may be more efficient to convert a user profile image via Pillow than to spawn an imagemagick process.
