### ISSUE TITLE
Wrong mimetype for CSS file

### ISSUE THREAD

**Issue by satyamtg** [openzim/python_scraperlib#38]
[This](https://github.com/openzim/python_scraperlib/files/5041291/lms-style-vendor.68e48093f5dd.zip) file in the PHZH zim made during [this](https://farm.openzim.org/pipeline/5f2ce0f92a0cfbdda0a33fcb) run in the ZimFarm has a wrong mimetype and hence we get the following error message in the console -
```
http://localhost:5232/phzh_core-english-one_en_2020-08/-/instance_assets/lms-style-vendor.68e48093f5dd.css
```
The file shall be detected as `text/css` to work but rather gets the mimetype as `text/troff`. This is basically due to the magic output where we get the following for this file -
```
>>> magic.detect_from_filename("lms-style-vendor.68e48093f5dd.css")
FileMagic(mime_type='text/troff', encoding='us-ascii', name='troff or preprocessor input, ASCII text, with very long lines')
```

**Comment by rgaudin** [comment]
Why are we using magic for those files? Wouldn't it be faster to use the filenames? Also, magic is notoriously poor quality with text files (no magic number obviously!)

**Comment by satyamtg** [comment]
> Why are we using magic for those files? Wouldn't it be faster to use the filenames? Also, magic is notoriously poor quality with text files (no magic number obviously!)

That's due to these lines -https://github.com/openzim/python_scraperlib/blob/master/src/zimscraperlib/zim/filesystem.py#L66-L70

I think what we shall follow in this order - 
Guess from filename and magic, if both are same, keep the mime, if both are different and magic output has text in it (not just text/plain), keep the guessed mime from the filename, If both are different and magic output doesn't have text, keep the magic mime.

**Comment by rgaudin** [comment]
> > Why are we using magic for those files? Wouldn't it be faster to use the filenames? Also, magic is notoriously poor quality with text files (no magic number obviously!)
> 
> That's due to these lines -https://github.com/openzim/python_scraperlib/blob/master/src/zimscraperlib/zim/filesystem.py#L66-L70
> 
> I think what we shall use the filename based guess if text and not just text/plain is present in the magic mime.

Exactly, we should use `if self.mime_type.startswith("text/")` instead.
