### ISSUE TITLE
mailto: links being rewritten while creating ZIM

### ISSUE THREAD

**Issue by satyamtg** [openzim/python_scraperlib#46]
The mailto: links are being accidentally rewritten by scraperlib while creating ZIMs. This is due to the fact that the urlparse method makes the e-mail ID as the path.
```
>>> import urllib.parse
>>> urllib.parse.urlparse("mailto:io.satyamtg@gmail.com?subject=haha")
ParseResult(scheme='mailto', netloc='', path='io.satyamtg@gmail.com', params='', query='subject=haha', fragment='')
```
This is the cause of some weird invalid links in openedx2zim such as this one
```
  The following links:
- ../../I/9a122b295d484793bbf1a33ab0217a69/digitallearning@phzh.ch?Subject=Feedback%20CORE%20English%20#01,%20v1:PHZH+W-IB+2019_E_1
(I/9a122b295d484793bbf1a33ab0217a69/digitallearning@phzh.ch) were not found in article A/9a122b295d484793bbf1a33ab0217a69/index.html
```

**Comment by rgaudin** [comment]
OK se shall exclude `mailto:` starting links then.

**Comment by kelson42** [comment]
Just in case, `tel:`, `geo:` and of course `data:` should not either (in case this is still not handled).
