### ISSUE TITLE
Update all scrapers to black 20 formatting

### ISSUE THREAD

**Issue by rgaudin** [openzim/python_scraperlib#58]
[black 20's changes](https://github.com/psf/black/blob/master/CHANGES.md#black-1) introduce new rules for comments that leads to changes in most python files of our scrapers.

We should convert [all scrapers](/openzim/python_scraperlib/wiki/Scrapers-list) to this new formatting now so that we don't pollute PRs with formatting changes.

Might be interesting to record the formatting commit [as specified here](https://github.com/psf/black#migrating-your-code-style-without-ruining-git-blame) for important repos (scraperlib, pylibzim, other?) ?

**Comment by satyamtg** [comment]
The following repositories have already been updated to black 20.8 formatting -
https://github.com/openzim/python_scraperlib
https://github.com/openzim/zimfarm
https://github.com/openzim/openedx
https://github.com/openzim/sotoki
https://github.com/openzim/warc2zim
https://github.com/openzim/gutenberg
https://github.com/openzim/youtube
https://github.com/openzim/ted

**Comment by satyamtg** [comment]
Closing this as most scrapers are already using black 20 formatting
