### ISSUE TITLE
Image optimization if the image extensions are incorrect

### ISSUE THREAD

**Issue by satyamtg** [openzim/python_scraperlib#64]
I just observed that sometimes youtube_dl has thumbnails which are `WEBP` but have a `.jpg` extension. This triggers an error while optimizing to a target as `WEBP` as the extension is then checked and its different from the source format. I think that we should change the extension if the format is not correct in `optimize_image`

**Comment by kelson42** [comment]
To me this is the bug, we should not rely on file extension if possible. Here it seems to be the case.

**Comment by satyamtg** [comment]
> To me this is the bug, we should not rely on file extension if possible. Here it seems to be the case.

We do not rely on extension. However, we check it as some tools do give errors if extensions are wrong (I remember it happened sometime back with sotoki)
